# Generated by Django 4.2.16 on 2026-08-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_flagged'),
        ('billing', '0002_payment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member'),
        ),
    ]
