"""
PyUpdater Client Config - Embed this in your built app.
Generated by: pyupdater make-spec -F main.py
"""
from pyupdater.client.config import ClientConfig

class Config(ClientConfig):
    APP_NAME = "FiveStarFitness"
    COMPANY_NAME = "5 Star Fitness"
    UPDATE_URLS = [
        "https://github.com/yourusername/GymWebApp/releases/download/v$VERSION/",
    ]
    PUBLIC_KEY = ""  # Filled in after `pyupdater keys -c`
    MAX_DOWNLOAD_RETRIES = 3
    RETRY_INTERVAL = 5