# Generated by Django 4.2.16 on 2026-08-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force the user to set a new password at their next login.'),
        ),
    ]
