# Generated by Django 4.2.16 on 2026-08-03 09:34

from django.db import migrations, models
import django.db.models.deletion


def backfill_check_in_datetime(apps, schema_editor):
    """Combine the legacy time-only check_in_time with its date column so the
    column can become a proper DateTimeField without losing any data."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE attendance_attendance "
            "SET check_in_time = date || ' ' || check_in_time "
            "WHERE check_in_time NOT LIKE '%-%'"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_flagged'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_check_in_datetime, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in_time']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='members.member'),
        ),
    ]
